### ISSUE TITLE
-i parameter not working

### ISSUE THREAD

**Issue by anonyme-x22** [Malvineous/dro2midi#6]
Hi,

It seems that the -i parameters isn't working anymore?
Also i did in the past a version which add Pitchbend selection, Input name for patch file as wall as instuments file and a parameter to insert the first program change as you did but we cannot disable it in this one.

I can give the source in order to imprve this version.
Everything need to be review of course.

Thanks in advance,
Have a good day,
Rgds,

**Comment by Malvineous** [comment]
I just tested `-i` and it works for me:
```
$ ./dro2midi testcases/bachbash.imf out.mid
>> Using similar match: Inst#117 @ line 192: Church Organ [20]

$ ./dro2midi -i testcases/bachbash.imf out.mid
>> Using similar match: Inst#000 @ line  41: Acoustic Grand Piano [1]
```
Here it chose the default instrument because there was no exact match in `insts.txt`.

Happy to merge patches if you open a PR and the code matches the existing coding style etc.

**Comment by anonyme-x22** [comment]
Hi,

You're right that was because my version use named file for instruments and instruments name, forgotten to rename to default.
I have Ultima VI done if you want.

It could usefull to get this feature as well as the pitch parameter in the last one!

Have a good day,
Rgds,
