### ISSUE TITLE
Is DROv2 supported now?

### ISSUE THREAD

**Issue by jotumn** [Malvineous/dro2midi#7]
I can only find v1.5 buid and it's not supported there.

**Comment by rofl0r** [comment]
yeah, it's supported now. you either have to build it from source yourself or get someone to provide a build for you. i'm assuming you want a windows version ?

**Comment by jotumn** [comment]
Great to hear that. Yeah, I wish someone made the builds available, I don't want to install VS and all that for a single app.

**Comment by rofl0r** [comment]
see #8

**Comment by Malvineous** [comment]
I've used @rofl0r's change to upload a new release with a Windows build.  You can find it at https://github.com/Malvineous/dro2midi/releases (under the win-x64 zip download).

Please let us know if it runs.

**Comment by jotumn** [comment]
Win10 Defender doesn't like the file:
![image](https://user-images.githubusercontent.com/16961866/217888822-8343aa37-364a-4cf5-bd1b-b94e5909a417.png)

After checking it with online antiviruses and finding nothing, I've added the file to the exceptions to download it. It works fine but I've got two questions. The default behaviour is to guess the instrument from inst.txt and I don't see any way to just say "use whatever instruments, just increment from 1". I have to copy-paste the NO XXX lines into inst.txt and do that manually. I wanted to input that into a DAW and set the instruments myself anyway.

The second thing is that it produces a single track MIDI file. Is there any way to make it a multitrack?

**Comment by rofl0r** [comment]
> Win10 Defender doesn't like the file:

the joys of using windows. the file was generated on a VM provided by github, so if there's a virus, then github itself is infected.

**Comment by Malvineous** [comment]
Glad it works.  Yes most virus checkers flag programs like this as suspicious because they are niche and not many people use them.

Those are limitations of dro2midi.  There are some instructions in the README about how to address it but it requires a lot of manual work, which is why I started libgamemusic instead.  Once that project progresses a little more, DRO2MIDI will be deprecated in favour of that.

I'm going to close this issue because the original point is now complete, but you can still reply here.

**Comment by jotumn** [comment]
Well, hopefully this will not dissuade people from downloading too much.

**Comment by Malvineous** [comment]
It's one of the reasons why I gave up on trying to build software for Windows and went web-based for the next version of Camoto.  It's just too problematic dealing with building software for Windows, let alone all the over-zealous malware scanners.
